NLMech: geometry::Fracture Class Reference
geometry::Fracture Class Reference
A class for fracture state of bonds.
#include <fracture.h>
Public Member Functions
bool addCrack (const double &time, const std::vector< util::Point3 > *nodes, const std::vector< std::vector< size_t >> *neighbor_list)
Sets fracture state according to the crack data.
Fracture (inp::FractureDeck *deck)
Constructor.
Fracture (inp::FractureDeck *deck, const std::vector< util::Point3 > *nodes, const std::vector< std::vector< size_t >> *neighbor_list)
Constructor.
std::vector< uint8_t > getBonds (const size_t &i) const
Returns the list of bonds of node i.
bool getBondState (const size_t &i, const size_t &j) const
Read bond state.
void print (int nt=0, int lvl=0) const
Prints the information about the instance of the object.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing information about the instance of the object.
void setBondState (const size_t &i, const size_t &j, const bool &state)
Sets the bond state.
Private Member Functions
void computeFracturedBondFd (const size_t &i, inp::EdgeCrack *crack, const std::vector< util::Point3 > *nodes, const std::vector< size_t > *neighbors)
Sets state of bond which intersect the pre-crack line as fractured.
Private Attributes
std::vector< std::vector< uint8_t > > d_fracture
Vector which stores the state of bonds.
inp::FractureDeck * d_fractureDeck_p
Interior flags deck.
Detailed Description
A class for fracture state of bonds.
This class provides method to read and modify fracture state of bonds
Constructor & Destructor Documentation
Fracture() [1/2]
geometry::Fracture::Fracture (inp::FractureDeck * deck, const std::vector< util::Point3 > * nodes, const std::vector< std::vector< size_t >> * neighbor_list)
Constructor.
Parameters
deck Input deck which contains user-specified information
nodes Pointer to nodal coordinates
neighbor_list Pointer to neighbor list
Fracture() [2/2]
geometry::Fracture::Fracture (inp::FractureDeck * deck) explicit
Constructor.
Parameters
deck Input deck which contains user-specified information
Member Function Documentation
addCrack()
bool geometry::Fracture::addCrack (const double & time, const std::vector< util::Point3 > * nodes, const std::vector< std::vector< size_t >> * neighbor_list)
Sets fracture state according to the crack data.
Parameters
time Actual simulation time
nodes Pointer to nodal coordinates
neighbor_list Pointer to neighbor list
Returns
True if one of the crack is applied at given time
computeFracturedBondFd()
void geometry::Fracture::computeFracturedBondFd (const size_t & i, inp::EdgeCrack * crack, const std::vector< util::Point3 > * nodes, const std::vector< size_t > * neighbors) private
Sets state of bond which intersect the pre-crack line as fractured.
Parameters
i Nodal id
crack Pointer to the pre-crack
nodes Pointer to nodal coordinates
neighbors Pointer to neighbors of node i
getBonds()
std::vector< uint8_t > geometry::Fracture::getBonds (const size_t & i) const
Returns the list of bonds of node i.
Parameters
i Nodal id
Returns
list Bonds of node i
getBondState()
bool geometry::Fracture::getBondState (const size_t & i, const size_t & j) const
Read bond state.
Parameters
i Nodal id
j Local id of bond in neighbor list of i
Returns
bool True if bond is fractured otherwise false
Referenced by test::testFracture().
print()
void geometry::Fracture::print (int nt = 0, int lvl = 0) const inline
Prints the information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
printStr()
std::string geometry::Fracture::printStr (int nt = 0, int lvl = 0) const
Returns the string containing information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
Returns
string String containing information about this object
Referenced by print().
setBondState()
void geometry::Fracture::setBondState (const size_t & i, const size_t & j, const bool & state)
Sets the bond state.
Parameters
i Nodal id
j Local id of bond in neighbor list of i
state State which is applied to the bond
Referenced by test::testFracture().
Field Documentation
d_fracture
std::vector<std::vector<uint8_t> > geometry::Fracture::d_fracture private
Vector which stores the state of bonds.
Given node i, vector d_fracture[i] is the list of state of bonds of node i.
We only use 1 bit per bond of node to store the state.
Referenced by Fracture().
The documentation for this class was generated from the following files:
/root/project/src/geometry/fracture.h
/root/project/src/geometry/fracture.cpp