NLMech: util::geometry Namespace Reference
util::geometry Namespace Reference
Provides geometrical methods such as point inside rectangle.
Functions
double angle (util::Point3 vec_1, util::Point3 vec_2, size_t dim, bool anticlock=false)
Computes angle between two vectors.
int direction (util::Point3 A, util::Point3 B, util::Point3 C)
Checks if the point C in on the line between A and B.
bool doLinesIntersect (util::Point3 A, util::Point3 B, util::Point3 C, util::Point3 D)
Checks if the two lines between A and B and between C and C interesect.
util::Point3 getCenter (const std::vector< util::Point3 > &nodes, const size_t &elem_type)
Computes the centroid of element.
std::pair< util::Point3, double > getCenterAndVol (const std::vector< util::Point3 > &nodes, const size_t &elem_type)
Computes the centroid and volume of element.
std::vector< util::Point3 > getCornerPoints (size_t dim, const std::pair< util::Point3, util::Point3 > &box)
Returns all corner points in the box.
double getTetVolume (const std::vector< util::Point3 > &nodes)
Computes the volume of tetrahedron.
double getTriangleArea (const std::vector< util::Point3 > &nodes)
Computes the area of triangle.
bool isPointinCircle (util::Point3 A, util::Point3 center, double radius)
Checks if the point A is within the circle with the center and the radisu.
bool isPointInsideAngledRectangle (util::Point3 x, double x_min, double x_max, double y_min, double y_max, double theta)
Checks if point is inside an angled rectangle.
bool isPointInsideCuboid (size_t dim, util::Point3 x, util::Point3 x_lbb, util::Point3 x_rtf)
Checks if point is inside a cuboid (rectangle in 2-d, line in 1-d)
bool isPointInsideRectangle (util::Point3 x, double x_min, double x_max, double y_min, double y_max)
Checks if point is inside a rectangle.
bool isPointInsideRectangle (util::Point3 x, util::Point3 x_lb, util::Point3 x_rt)
Checks if point is inside a rectangle.
bool onLine (util::Point3 A, util::Point3 B, util::Point3 C)
Checks if the point C in on the between A and B.
Detailed Description
Provides geometrical methods such as point inside rectangle.
Function Documentation
angle()
double util::geometry::angle (util::Point3 vec_1, util::Point3 vec_2, size_t dim, bool anticlock = false)
Computes angle between two vectors.
Parameters
vec_1 Vector 1
vec_2 Vector 2
dim Dimension
anticlock Angle convention
Returns
angle Angle between vector 1 and 2
Referenced by angle().
direction()
int util::geometry::direction (util::Point3 A, util::Point3 B, util::Point3 C)
Checks if the point C in on the line between A and B.
Parameters
A Point 1
B Point 2
C Point 3
Returns
Direction
Referenced by doLinesIntersect().
doLinesIntersect()
bool util::geometry::doLinesIntersect (util::Point3 A, util::Point3 B, util::Point3 C, util::Point3 D)
Checks if the two lines between A and B and between C and C interesect.
Parameters
A Start point of the first line
B End point of the first line
C Start point of the second line
D End point of the second line
Returns
interesction
Referenced by model::FDModel< T >::is_reaction_force().
getCenter()
util::Point3 util::geometry::getCenter (const std::vector< util::Point3 > & nodes, const size_t & elem_type)
Computes the centroid of element.
Parameters
nodes Vertices of the element
elem_type Element type
Returns
Point Centroid
getCenterAndVol()
std::pair< util::Point3, double > util::geometry::getCenterAndVol (const std::vector< util::Point3 > & nodes, const size_t & elem_type)
Computes the centroid and volume of element.
Parameters
nodes Vertices of the element
elem_type Element type
Returns
Point-volume Pair of centroid and volume
Referenced by fe::Mesh::nodesAtCentroid().
getCornerPoints()
std::vector< util::Point3 > util::geometry::getCornerPoints (size_t dim, const std::pair< util::Point3, util::Point3 > & box)
Returns all corner points in the box.
Parameters
dim Dimension of the box
box Pair of points representing cuboid (rectangle in 2d)
Returns
Vector Vector of corner points
getTetVolume()
double util::geometry::getTetVolume (const std::vector< util::Point3 > & nodes)
Computes the volume of tetrahedron.
Parameters
nodes Vertices of the tetrahedron
Returns
area Area of tetrahedron
Referenced by getCenterAndVol().
getTriangleArea()
double util::geometry::getTriangleArea (const std::vector< util::Point3 > & nodes)
Computes the area of triangle.
Parameters
nodes Vertices of the triangle
Returns
area Area of triangle
Referenced by getCenterAndVol().
isPointinCircle()
bool util::geometry::isPointinCircle (util::Point3 A, util::Point3 center, double radius)
Checks if the point A is within the circle with the center and the radisu.
Parameters
A Point 1
center Center of the circle
radius Radius of the cricle
Returns
Direction
Referenced by loading::ULoading::ULoading().
isPointInsideAngledRectangle()
bool util::geometry::isPointInsideAngledRectangle (util::Point3 x, double x_min, double x_max, double y_min, double y_max, double theta)
Checks if point is inside an angled rectangle.
Parameters
x Point
x_min X coordinate of left-bottom corner point
x_max X coordinate of right-top corner point
y_min Y coordinate of left-bottom corner point
y_max Y coordinate of right-top corner point
theta Angle of orientation of rectangle from x-axis
Returns
bool True if point inside rectangle, else false
Referenced by loading::FLoading::FLoading(), and loading::ULoading::ULoading().
isPointInsideCuboid()
bool util::geometry::isPointInsideCuboid (size_t dim, util::Point3 x, util::Point3 x_lbb, util::Point3 x_rtf)
Checks if point is inside a cuboid (rectangle in 2-d, line in 1-d)
Parameters
dim Dimension
x Point
x_lbb Coordinate of left-bottom-back corner point
x_rtf Coordinate of right-top-front corner point
Returns
bool True if point inside cuboid, else false
Referenced by geometry::DampingGeom::computeDampingCoefficient(), and loading::FLoading::FLoading().
isPointInsideRectangle() [1/2]
bool util::geometry::isPointInsideRectangle (util::Point3 x, double x_min, double x_max, double y_min, double y_max)
Checks if point is inside a rectangle.
Parameters
x Point
x_min X coordinate of left-bottom corner point
x_max X coordinate of right-top corner point
y_min Y coordinate of left-bottom corner point
y_max Y coordinate of right-top corner point
Returns
bool True if point inside rectangle, else false
Referenced by model::FDModel< T >::checkOutputCriteria(), geometry::DataInterior::DataInterior(), tools::pp::Compute::decomposeSearchNodes(), loading::FLoading::FLoading(), geometry::ComputeInterior::getInteriorFlag(), tools::pp::Compute::getRectsAndNodesForCrackTip(), tools::pp::Compute::init(), tools::pp::Compute::listElemsAndNodesInDomain(), and loading::ULoading::ULoading().
isPointInsideRectangle() [2/2]
bool util::geometry::isPointInsideRectangle (util::Point3 x, util::Point3 x_lb, util::Point3 x_rt)
Checks if point is inside a rectangle.
Parameters
x Point
x_lb Coordinate of left-bottom corner point
x_rt Coordinate of right-top corner point
Returns
bool True if point inside rectangle, else false
onLine()
bool util::geometry::onLine (util::Point3 A, util::Point3 B, util::Point3 C)
Checks if the point C in on the between A and B.
Parameters
A Start point of the first line
B End point of the first line
C Point to test
Returns
interesction
Referenced by doLinesIntersect().