NLMech: rw::reader Namespace Reference
rw::reader Namespace Reference
Collection of methods and database related to reading.
Data Structures
class MshReader
A class to read Gmsh (msh) mesh files.
class VtkReader
A class to read VTK (.vtu) mesh files.
Functions
CSV specific functions
void readCsvFile (const std::string &filename, size_t dim, std::vector< util::Point3 > *nodes, std::vector< double > *volumes)
Reads mesh data into node file and element file.
VTU specific functions
void readVtuFile (const std::string &filename, size_t dim, std::vector< util::Point3 > *nodes, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t >> *nec, std::vector< double > *volumes, bool is_fd=false)
Reads mesh data into node file and element file.
void readVtuFileNodes (const std::string &filename, size_t dim, std::vector< util::Point3 > *nodes, bool ref_config=false)
Reads nodal coordinates.
bool vtuHasPointData (const std::string &filename, const std::string &tag)
Checks if file has needed data.
bool vtuHasCellData (const std::string &filename, const std::string &tag)
Checks if file has needed data.
std::vector< std::string > readVtuFilePointTags (const std::string &filename)
Reads all point data tags.
std::vector< std::string > readVtuFileCellTags (const std::string &filename)
Reads all cell data tags.
void readVtuFileCells (const std::string &filename, size_t dim, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t >> *nec)
Reads cell data, i.e. element-node connectivity and node-element connectivity.
void readVtuFileRestart (const std::string &filename, std::vector< util::Point3 > *u, std::vector< util::Point3 > *v, const std::vector< util::Point3 > *X=nullptr)
Reads mesh data into node file and element file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< uint8_t > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< size_t > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< int > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< float > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< double > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< util::Point3 > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< util::SymMatrix3 > *data)
Reads data of specified tag from the vtu file.
bool readVtuFilePointData (const std::string &filename, const std::string &tag, std::vector< util::Matrix33 > *data)
Reads data of specified tag from the vtu file.
bool readVtuFileCellData (const std::string &filename, const std::string &tag, std::vector< float > *data)
Reads data of specified tag from the vtu file.
bool readVtuFileCellData (const std::string &filename, const std::string &tag, std::vector< double > *data)
Reads data of specified tag from the vtu file.
bool readVtuFileCellData (const std::string &filename, const std::string &tag, std::vector< util::Point3 > *data)
Reads data of specified tag from the vtu file.
bool readVtuFileCellData (const std::string &filename, const std::string &tag, std::vector< util::SymMatrix3 > *data)
Reads data of specified tag from the vtu file.
bool readVtuFileCellData (const std::string &filename, const std::string &tag, std::vector< util::Matrix33 > *data)
Reads data of specified tag from the vtu file.
MSH specific functions
void readMshFile (const std::string &filename, size_t dim, std::vector< util::Point3 > *nodes, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t >> *nec, std::vector< double > *volumes, bool is_fd=false)
Reads mesh data into node file and element file.
void readMshFileRestart (const std::string &filename, std::vector< util::Point3 > *u, std::vector< util::Point3 > *v, const std::vector< util::Point3 > *X=nullptr)
Reads mesh data into node file and element file.
bool readMshFilePointData (const std::string &filename, const std::string &tag, std::vector< double > *data)
Reads data of specified tag from the vtu file.
Detailed Description
Collection of methods and database related to reading.
This namespace provides methods and data members specific to reading of the mesh data. Currently, .csv, .vtu and .msh files are supported.
Function Documentation
readCsvFile()
void rw::reader::readCsvFile (const std::string & filename, size_t dim, std::vector< util::Point3 > * nodes, std::vector< double > * volumes)
Reads mesh data into node file and element file.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of nodes data
volumes Vector holding volume of the nodes
Referenced by fe::Mesh::createData().
readMshFile()
void rw::reader::readMshFile (const std::string & filename, size_t dim, std::vector< util::Point3 > * nodes, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t >> * nec, std::vector< double > * volumes, bool is_fd = false)
Reads mesh data into node file and element file.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of nodes data
element_type Type of element
num_elem Number of elements
enc Vector holding element-node connectivity
nec Vector holding node-element connectivity
volumes Vector holding volume of the nodes
is_fd Flag indicating if this mesh is for finite_difference simulation
Referenced by fe::Mesh::createData().
readMshFilePointData()
bool rw::reader::readMshFilePointData (const std::string & filename, const std::string & tag, std::vector< double > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readMshFileRestart()
void rw::reader::readMshFileRestart (const std::string & filename, std::vector< util::Point3 > * u, std::vector< util::Point3 > * v, const std::vector< util::Point3 > * X = nullptr)
Reads mesh data into node file and element file.
Parameters
filename Name of mesh file
u Pointer to vector of nodal displacement
v Pointer to vector of nodal velocity
X Pointer to vector of nodal reference position (Optional)
Referenced by tools::pp::Compute::Compute(), and model::FDModel< T >::restart().
readVtuFile()
void rw::reader::readVtuFile (const std::string & filename, size_t dim, std::vector< util::Point3 > * nodes, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t >> * nec, std::vector< double > * volumes, bool is_fd = false)
Reads mesh data into node file and element file.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of nodes data
element_type Type of element
num_elem Number of elements
enc Vector holding element-node connectivity
nec Vector holding node-element connectivity
volumes Vector holding volume of the nodes
is_fd Flag indicating if this mesh is for finite_difference simulation
readVtuFileCellData() [1/5]
bool rw::reader::readVtuFileCellData (const std::string & filename, const std::string & tag, std::vector< double > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFileCellData() [2/5]
bool rw::reader::readVtuFileCellData (const std::string & filename, const std::string & tag, std::vector< float > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFileCellData() [3/5]
bool rw::reader::readVtuFileCellData (const std::string & filename, const std::string & tag, std::vector< util::Matrix33 > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFileCellData() [4/5]
bool rw::reader::readVtuFileCellData (const std::string & filename, const std::string & tag, std::vector< util::Point3 > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFileCellData() [5/5]
bool rw::reader::readVtuFileCellData (const std::string & filename, const std::string & tag, std::vector< util::SymMatrix3 > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFileCells()
void rw::reader::readVtuFileCells (const std::string & filename, size_t dim, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t >> * nec)
Reads cell data, i.e. element-node connectivity and node-element connectivity.
Parameters
filename Name of mesh file
dim Dimension
element_type Type of element
num_elem Number of elements
enc Element-node connectivity
nec Node-element connectivity
Referenced by fe::Mesh::createData().
readVtuFileCellTags()
std::vector< std::string > rw::reader::readVtuFileCellTags (const std::string & filename)
Reads all cell data tags.
Parameters
filename Name of mesh file
Returns
List List of point data tags
readVtuFileNodes()
void rw::reader::readVtuFileNodes (const std::string & filename, size_t dim, std::vector< util::Point3 > * nodes, bool ref_config = false)
Reads nodal coordinates.
Parameters
filename Name of mesh file
dim Dimension
nodes Vector of nodes data
ref_config Flag which specifies if we need to subtract the displacement from nodes obtained from vtu file to get reference position of nodes
Referenced by fe::Mesh::createData().
readVtuFilePointData() [1/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< double > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFilePointData() [2/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< float > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFilePointData() [3/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< int > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFilePointData() [4/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< size_t > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFilePointData() [5/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< uint8_t > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
Referenced by tools::pp::Compute::Compute(), and fe::Mesh::createData().
readVtuFilePointData() [6/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< util::Matrix33 > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFilePointData() [7/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< util::Point3 > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFilePointData() [8/8]
bool rw::reader::readVtuFilePointData (const std::string & filename, const std::string & tag, std::vector< util::SymMatrix3 > * data)
Reads data of specified tag from the vtu file.
Parameters
filename Name of mesh file
tag Name of point data to be read from .vtu file
data Pointer to vector of point data
Returns
bool True if found the data in file
readVtuFilePointTags()
std::vector< std::string > rw::reader::readVtuFilePointTags (const std::string & filename)
Reads all point data tags.
Parameters
filename Name of mesh file
Returns
List List of point data tags
readVtuFileRestart()
void rw::reader::readVtuFileRestart (const std::string & filename, std::vector< util::Point3 > * u, std::vector< util::Point3 > * v, const std::vector< util::Point3 > * X = nullptr)
Reads mesh data into node file and element file.
Parameters
filename Name of mesh file
u Pointer to vector of nodal displacement
v Pointer to vector of nodal velocity
X Pointer to vector of nodal reference position (Optional)
Referenced by tools::pp::Compute::Compute(), and model::FDModel< T >::restart().
vtuHasCellData()
bool rw::reader::vtuHasCellData (const std::string & filename, const std::string & tag)
Checks if file has needed data.
Parameters
filename Name of mesh file
tag Tag name of data
Returns
True If file has data otherwise false
vtuHasPointData()
bool rw::reader::vtuHasPointData (const std::string & filename, const std::string & tag)
Checks if file has needed data.
Parameters
filename Name of mesh file
tag Tag name of data
Returns
True If file has data otherwise false
Referenced by tools::pp::Compute::Compute().