NLMech: util::methods Namespace Reference
util::methods Namespace Reference
Provides fast methods to add/subtract list of data, to find maximum/minimum from list of data.
Functions
double add (const std::vector< double > &data)
Returns the sum of data.
float add (const std::vector< float > &data)
Returns the sum of data.
double max (const std::vector< double > &data, size_t *i=nullptr)
Returns the maximum from list of data.
float max (const std::vector< float > &data, size_t *i=nullptr)
Returns the maximum from list of data.
util::Point3 maxLength (const std::vector< util::Point3 > &data)
Returns the maximum length of point from list of points.
double min (const std::vector< double > &data, size_t *i=nullptr)
Returns the minimum from list of data.
float min (const std::vector< float > &data, size_t *i=nullptr)
Returns the minimum from list of data.
Detailed Description
Provides fast methods to add/subtract list of data, to find maximum/minimum from list of data.
Function Documentation
add() [1/2]
double util::methods::add (const std::vector< double > & data)
Returns the sum of data.
Parameters
data List of real numbers
Returns
sum Sum of the numbers
Referenced by tools::pp::Compute::computeJIntegral(), and model::Output::Output().
add() [2/2]
float util::methods::add (const std::vector< float > & data)
Returns the sum of data.
Parameters
data List of real numbers
Returns
sum Sum of the numbers
max() [1/2]
double util::methods::max (const std::vector< double > & data, size_t * i = nullptr)
Returns the maximum from list of data.
Parameters
data List of real numbers
i Pointer to store the id where maximum occurs
Returns
max Maximum value
Referenced by model::FDModel< T >::checkOutputCriteria(), and tools::pp::Compute::updateCrack().
max() [2/2]
float util::methods::max (const std::vector< float > & data, size_t * i = nullptr)
Returns the maximum from list of data.
Parameters
data List of real numbers
i Pointer to store the id where maximum occurs
Returns
max Maximum value
maxLength()
util::Point3 util::methods::maxLength (const std::vector< util::Point3 > & data)
Returns the maximum length of point from list of points.
Parameters
data List of points
Returns
max Maximum length of point
min() [1/2]
double util::methods::min (const std::vector< double > & data, size_t * i = nullptr)
Returns the minimum from list of data.
Parameters
data List of real numbers
i Pointer to store the id where minimum occurs
Returns
min Minimum value
Referenced by tools::pp::Compute::findTipInRects().
min() [2/2]
float util::methods::min (const std::vector< float > & data, size_t * i = nullptr)
Returns the minimum from list of data.
Parameters
data List of real numbers
i Pointer to store the id where minimum occurs
Returns
min Minimum value