NLMech: util::Point3 Struct Reference
util::Point3 Struct Reference
A structure to represent 3d vectors.
#include <point.h>
Public Member Functions
double angle (Point3 b) const
Computes the angle between vector given by this and the vector b.
Point3 cross (const Point3 &b) const
Computes the cross product between this vector and given vector.
double dist (const Point3 &b) const
Computes the distance between a given point from this point.
double dot (const Point3 &b) const
Computes the dot product of this vector with another point.
double length () const
Computes the Euclidean length of the vector.
double lengthSq () const
Computes the Euclidean length of the vector.
Point3 ()
Constructor.
Point3 (const Point3 &p)
Copy constructor.
Point3 (const std::vector< double > &p)
Constructor.
template<class T >
Point3 (T x, T y, T z)
Constructor.
template<class T >
Point3 (T x[3])
Constructor.
void print (int nt=0, int lvl=0) const
Prints the information.
std::string printStr (int nt=0, int lvl=0) const
Prints the information.
Point3 project (const Point3 &b, bool is_unit=false) const
Computes projection of vector on this vector.
Point3 projectNormal (const Point3 &b, bool is_unit=false) const
Computes projection of vector on plane with normal as this vector.
util::Matrix33 toMatrix ()
Computes the dot product of the vector and its transpose.
util::Matrix33 toMatrix (const util::Point3 b)
Computes the dot product of the vector x and the transpose of y.
util::Vector3 toVector ()
Converts the point to an blaze vector.
Point3 unit ()
Returns the unit vector.
Point3 unit () const
Returns the unit vector.
Data Fields
double d_x
the x coordinate
double d_y
the y coordinate
double d_z
the z coordinate
Group operators
Point3 & operator+= (const double b)
Add a scalar to the point.
Point3 & operator-= (const double b)
Substracts a scalar to the point.
Point3 & operator*= (const double b)
Multiplies a scalar to the point.
Point3 & operator+= (const Point3 &b)
Adds a point.
Point3 & operator-= (const Point3 &b)
Substracts a point.
Point3 & operator*= (const Point3 &b)
Multilpies a point.
Point3 & operator/= (const double b)
Divides a point by a scalr.
double & operator[] (size_t i)
Access the 0th componnent of a point.
const double & operator[] (size_t i) const
Access the 0th componnent of a point.
Point3 operator+ (Point3 lhs, const Point3 &rhs)
Adds two points.
Point3 operator- (Point3 lhs, const Point3 &rhs)
Substracts two points.
double operator* (Point3 lhs, const Point3 rhs)
Multiplies a constant to the point.
Point3 operator* (Point3 lhs, const double rhs)
Adds two points.
Point3 operator+ (Point3 lhs, const double rhs)
Adds a scalar to the point.
Point3 operator+ (const double lhs, Point3 rhs)
Adds two points.
Point3 operator- (Point3 lhs, const double rhs)
Substracts a scalar to the point.
Point3 operator- (const double lhs, Point3 rhs)
Substracts a scalar to the point.
Point3 operator* (const double lhs, Point3 rhs)
Substracts a scalar to the point.
Point3 operator/ (Point3 lhs, const double rhs)
Divedes a scalar to the point.
std::ostream & operator<< (std::ostream &os, const Point3 p)
Print the point's vlaue to the standard output stream.
Detailed Description
A structure to represent 3d vectors.
Constructor & Destructor Documentation
Point3() [1/4]
template<class T > util::Point3::Point3 (T x, T y, T z) inline
Constructor.
Parameters
x The x coordinate
y The y coordinate
z The z coordinate
Point3() [2/4]
template<class T > util::Point3::Point3 (T x[3]) inline explicit
Constructor.
Parameters
x The coordinate vector
Point3() [3/4]
util::Point3::Point3 (const std::vector< double > & p) inline explicit
Constructor.
Parameters
p Point
Point3() [4/4]
util::Point3::Point3 (const Point3 & p) inline
Copy constructor.
Parameters
p Point
Member Function Documentation
angle()
double util::Point3::angle (Point3 b) const inline
Computes the angle between vector given by this and the vector b.
Parameters
b Another vector
Returns
Value a dot product
cross()
Point3 util::Point3::cross (const Point3 & b) const inline
Computes the cross product between this vector and given vector.
Parameters
b Another vector
Returns
Vector Cross product
dist()
double util::Point3::dist (const Point3 & b) const inline
Computes the distance between a given point from this point.
Parameters
b Another point
Returns
Value Distance between the two points
Referenced by util::function::doubleGaussian2d(), tools::pp::Compute::findNode(), util::function::gaussian2d(), tools::pp::Compute::interpolateUV(), and inp::Input::setFractureDeck().
dot()
double util::Point3::dot (const Point3 & b) const inline
Computes the dot product of this vector with another point.
Parameters
b Another vector
Returns
Value a dot product
Referenced by util::geometry::angle(), tools::pp::Compute::getContourContribJInt(), material::pd::RNPBond::getS(), project(), and projectNormal().
length()
double util::Point3::length () const inline
Computes the Euclidean length of the vector.
Returns
Length Euclidean length of the vector
Referenced by material::pd::ElasticState::dirac_delta(), material::pd::ElasticState::getBondEF(), material::pd::RNPBond::getBondForceDirection(), material::pd::ElasticState::getBondForceDirection(), tools::pp::Compute::getContourContribJInt(), material::pd::ElasticState::K_modulus_tensor(), project(), projectNormal(), and unit().
lengthSq()
double util::Point3::lengthSq () const inline
Computes the Euclidean length of the vector.
Returns
Length Euclidean length of the vector
operator*=() [1/2]
Point3& util::Point3::operator*= (const double b) inline
Multiplies a scalar to the point.
Parameters
b Scalar factor
Returns
Scaled point
operator*=() [2/2]
Point3& util::Point3::operator*= (const Point3 & b) inline
Multilpies a point.
Parameters
b Point
Returns
Point-wise product of the two points
operator+=() [1/2]
Point3& util::Point3::operator+= (const double b) inline
Add a scalar to the point.
Parameters
b Scalar factor
Returns
Scaled point
operator+=() [2/2]
Point3& util::Point3::operator+= (const Point3 & b) inline
Adds a point.
Parameters
b Point
Returns
Sum of the two points
operator-=() [1/2]
Point3& util::Point3::operator-= (const double b) inline
Substracts a scalar to the point.
Parameters
b Scalar factor
Returns
Shifted point
operator-=() [2/2]
Point3& util::Point3::operator-= (const Point3 & b) inline
Substracts a point.
Parameters
b Point
Returns
Difference of the two points
operator/=()
Point3& util::Point3::operator/= (const double b) inline
Divides a point by a scalr.
Parameters
b Scalar factor
Returns
Scaled point
operator[]() [1/2]
double& util::Point3::operator[] (size_t i) inline
Access the 0th componnent of a point.
Parameters
i Index
Returns
The i-th index of the point
operator[]() [2/2]
const double& util::Point3::operator[] (size_t i) const inline
Access the 0th componnent of a point.
Parameters
i Index
Returns
The i-th index of the point
print()
void util::Point3::print (int nt = 0, int lvl = 0) const inline
Prints the information.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
printStr()
std::string util::Point3::printStr (int nt = 0, int lvl = 0) const inline
Prints the information.
Parameters
nt Number of tabs to append before printing
lvl Information level (higher means more information)
Returns
Manipulated string
Referenced by tools::pp::Compute::computeJIntegral(), print(), and fe::QuadData::printStr().
project()
Point3 util::Point3::project (const Point3 & b, bool is_unit = false) const inline
Computes projection of vector on this vector.
Parameters
b Another vector
is_unit Is a unit vector
Returns
Vector Projection vector
projectNormal()
Point3 util::Point3::projectNormal (const Point3 & b, bool is_unit = false) const inline
Computes projection of vector on plane with normal as this vector.
Parameters
b Another vector
is_unit Is a unit vector
Returns
Vector Projection vector
toMatrix() [1/2]
util::Matrix33 util::Point3::toMatrix () inline
Computes the dot product of the vector and its transpose.
Returns
dot(x,x.T)
Referenced by material::pd::ElasticState::deformation_gradient(), material::pd::ElasticState::K_modulus_tensor(), and material::pd::ElasticState::K_shape_tensor().
toMatrix() [2/2]
util::Matrix33 util::Point3::toMatrix (const util::Point3 b) inline
Computes the dot product of the vector x and the transpose of y.
Parameters
b The node b
Returns
dot(x,y.T)
toVector()
util::Vector3 util::Point3::toVector () inline
Converts the point to an blaze vector.
Returns
Point as blaze vector 3D
Referenced by material::pd::ElasticState::getStress().
unit() [1/2]
Point3 util::Point3::unit () inline
Returns the unit vector.
Returns
Vector Unit vector
Referenced by angle().
unit() [2/2]
Point3 util::Point3::unit () const inline
Returns the unit vector.
Returns
Vector Unit vector
Friends And Related Function Documentation
operator* [1/3]
Point3 operator* (const double lhs, Point3 rhs) friend
Substracts a scalar to the point.
Parameters
lhs Left-hand side
rhs Left-hand side
Returns
Shifted point
operator* [2/3]
Point3 operator* (Point3 lhs, const double rhs) friend
Adds two points.
Parameters
lhs Left-hand side
rhs Left-hand side
Returns
Sum of the two points
operator* [3/3]
double operator* (Point3 lhs, const Point3 rhs) friend
Multiplies a constant to the point.
Parameters
lhs Left-hand side
rhs Left-hand side
Returns
Scaled point
operator+ [1/3]
Point3 operator+ (const double lhs, Point3 rhs) friend
Adds two points.
Parameters
lhs Left-hand side
rhs Left-hand side
Returns
Sum of the two points
operator+ [2/3]
Point3 operator+ (Point3 lhs, const double rhs) friend
Adds a scalar to the point.
Parameters
lhs Left-hand side
rhs Left-hand side
Returns
Shifted point
operator+ [3/3]
Point3 operator+ (Point3 lhs, const Point3 & rhs) friend
Adds two points.
Parameters
lhs Left-hand side
rhs Left-hand side
Returns
Sum of the two points
operator- [1/3]
Point3 operator- (const double lhs, Point3 rhs) friend
Substracts a scalar to the point.
Parameters
lhs Left-hand side
rhs Left-hand side
Returns
Shifted point
operator- [2/3]
Point3 operator- (Point3 lhs, const double rhs) friend
Substracts a scalar to the point.
Parameters
lhs Left-hand side
rhs Left-hand side
Returns
Shifted point
operator- [3/3]
Point3 operator- (Point3 lhs, const Point3 & rhs) friend
Substracts two points.
Parameters
lhs Left-hand side
rhs Left-hand side
Returns
Difference of the two points
operator/
Point3 operator/ (Point3 lhs, const double rhs) friend
Divedes a scalar to the point.
Parameters
lhs Left-hand side
rhs Left-hand side
Returns
Scaled point
operator<<
std::ostream& operator<< (std::ostream & os, const Point3 p) friend
Print the point's vlaue to the standard output stream.
Parameters
os Standard output stream
p Point
Returns
The standard out stream
The documentation for this struct was generated from the following file:
/root/project/src/util/point.h